
spring:
  kafka:
    consumer:
      bootstrap-server: "127.0.0.1:9092"
      auto-offset-reset: "earliest"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"