spring:
  kafka:
    producer:
      bootstrap-server: "127.0.0.1:9092"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"